// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD7dndoLqK7Ne9o3k9Zoh-mx4ryerwWbc',
    appId: '1:373500339760:web:03e231b95cde31c7a2eff5',
    messagingSenderId: '373500339760',
    projectId: 'monney-planning-app',
    authDomain: 'monney-planning-app.firebaseapp.com',
    storageBucket: 'monney-planning-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvkQ7Mer55nZPZCJ5H1M772EfGXPPSwbA',
    appId: '1:373500339760:android:673ced601c805c68a2eff5',
    messagingSenderId: '373500339760',
    projectId: 'monney-planning-app',
    storageBucket: 'monney-planning-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_RNTxiMtWnCdK_Cmu8NIUObE-aK2SGwg',
    appId: '1:373500339760:ios:b9f174d0925b90c3a2eff5',
    messagingSenderId: '373500339760',
    projectId: 'monney-planning-app',
    storageBucket: 'monney-planning-app.firebasestorage.app',
    iosBundleId: 'com.example.moneyPlanningApp',
  );
}
